### PR TITLE
Validates the Modal Inputs

### LINKED ISSUE #52: Validate User Input for Modal
Make sure the inputs from the user make sense before submitting. Add an error message if something is incorrect.

Requirements for a post:

- Text inputs must not be blank
- Date must be valid
- Time must be valid
- Limit length of input
- Check for HTML injection

### LINKED ISSUE #61: Check for Duplicate Events
When trying to submit, I clicked the button multiple times and when it finished loading, it add multiple of the same events onto the posts list.

image

### LINKED ISSUE #74: Add Indicator that Post has been Added
Since the feed only shows the day-of posts, it's hard for users to know if their post successfully got added so it would be great to let the user know it's been added or specify that posts only show up on the `all-post` if it's the day of!

### PR DESCRIPTION
**Pull request by ubahl**
Does not allow the user to submit the modal unless modal constraints are met, and alerts the user to the errors.

Modal constraints (Resolves #52):

- Text inputs must not be blank
- Month must be valid, day is a valid day in the month
- Time must be valid: hours and minute fall in the standard 12 hour clock, and start time is before end time
- Checks for HTML injection by replacing tags with HTML code
- The maximum length of the text inputs are limited (50 - 100 characters, depending on input). This is in response to our user feedback collection where a user was able to exceed the maximum byte limit for strings with their input.

Screenshot 2020-08-17 at 10 02 14 PM
Screenshot 2020-08-17 at 10 07 53 PM
Screenshot 2020-08-17 at 10 19 57 PM

If one of these requirements is violated, visually marks the field. Also writes the error at the bottom with accessibility in mind. This is accomplished by having two arrays simultaneously updated: one for the ids of the invalid inputs, and one for error strings.

Screenshot 2020-08-17 at 9 53 22 PM

Resolves #61. Disables the submit button once it has been clicked, so multiple submissions cannot be sent.

Resolves #74. Displays a modal which indicates once the form has been submitted. Focus is trapped in the modal and focuses back on the "create a post button" on close.
Screenshot 2020-08-17 at 9 53 37 PM

Lastly, adds a bio for the contact page.

### CODE REVIEW

File: src/main/webapp/assets/js/feedScript.js [hunk 1]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
  * @return {void}
  */
 async function submitModal() {
-  const collegeId = (new URLSearchParams(window.location.search)).get('collegeid');
+  // Disable multiple submissions.
+  submitModalButton.disabled = true;
```
Comment (mirrorkeydev) [inline src/main/webapp/assets/js/feedScript.js:618]: smart!

File: src/main/webapp/assets/js/feedScript.js [hunk 2]
```diff
@@ -679,11 +892,19 @@ document.addEventListener('keydown', function(e) {
...
+    }
   } else { // If user is trying to go to the next element, make sure it wraps to the top.
     if (document.activeElement === submitModalButton) {
       modalCard.focus();
       e.preventDefault();
     }
+    if (document.activeElement == modalSubmittedText) {
+      modalSubmitted.focus();
+      e.preventDefault();
+    }
```
Comment (mirrorkeydev) [inline src/main/webapp/assets/js/feedScript.js:907]: Small nit but use `===` wherever possible! :) ([src](https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons))

File: src/main/webapp/find-events.html [hunk 3]
```diff
@@ -64,54 +64,57 @@ <h1 id="find-events-title" tabindex="0">find events</h1>
           </div>
         </div>
         <div id="all-posts">
-          <button id="create-post-button" type="button" tabindex="0" aria-label="create a post">create a post</button>
+          <button aria-label="create a post" id="create-post-button" tabindex="0" type="button">create a post</button>
```
Comment (mirrorkeydev) [inline src/main/webapp/find-events.html:67]: I believe `aria-labels` are only needed if there isn't visible/screen-reader accessible text (see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute), but lemme know if I'm missing something here!

Comment (mirrorkeydev) [reply src/main/webapp/find-events.html:67]: So for the case of using placeholder text as the label (like in the modal), `aria-label` is helpful because screenreaders don't always read placeholders, but this button does have normal containing text so I think it doesn't need it

File: src/main/webapp/assets/js/feedScript.js (hunk 1 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:618]: thank you! :)

File: src/main/webapp/assets/js/feedScript.js (hunk 2 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:907]: Ah good to know!

File: src/main/webapp/assets/css/feedStyle.css [hunk 4]
```diff
@@ -212,13 +207,39 @@ select {
   color: #404040;
 }
 
+#modal-submitted {
```
Comment (areetaw) [inline src/main/webapp/assets/css/feedStyle.css:210]: Love this!!

File: src/main/webapp/assets/js/feedScript.js [hunk 5]
```diff
@@ -123,6 +129,8 @@ async function onLoad() {
   modalForm = document.getElementById('modal-form');
   toggleLegendButton = document.getElementById('toggle-legend-button');
   modalCard = document.getElementById('modal-create-post');
+  modalSubmitted = document.getElementById('modal-submitted');
+  modalSubmittedText = document.getElementById('modal-submitted-title');
```
Comment (areetaw) [inline src/main/webapp/assets/js/feedScript.js:133]: Should the id for this be modal-submitted-text as well?

File: src/main/webapp/assets/js/feedScript.js [hunk 6]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+ * Goes through the elements and replaces the tags with their HTML equivalent.
+ * @param {array} formElements
+ * @return {void}
+ */
+function disableInjection(formElements) {
   for (let i = 0; i < formElements.length - 1; i++) {
-    if (formElements[i].value.length == 0) {
-      return;
+    let eltValue = formElements[i].value;
+    eltValue = eltValue.replace(/</g, '&lt;').replace(/>/g, '&gt;');
```
Comment (areetaw) [inline src/main/webapp/assets/js/feedScript.js:658]: What's this? :0

File: src/main/webapp/find-events.html (hunk 3 above)
Comment (ubahl) [reply src/main/webapp/find-events.html:67]: Good point!! I'll remove it

File: src/main/webapp/assets/js/feedScript.js [hunk 7]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+/**
+ * Goes through the form elements. If it is a text input, adds an error if it is blank.
+ * @param {array} invalidIds
+ * @param {array} errorMessages
+ * @param {array} formElements
+ * @return {void}
+ */
+function validateModalText(invalidIds, errorMessages, formElements) {
+  for (let i = 0; i < formElements.length; i++) {
+    if (formElements[i].type === 'text' || formElements[i].type === 'textarea') {
```
Comment (areetaw) [inline src/main/webapp/assets/js/feedScript.js:798]: camelCase for textarea?

File: src/main/webapp/assets/js/feedScript.js [hunk 8]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+      if (isBlank(formElements[i].value)) {
+        invalidIds.push(formElements[i].id);
+        const errorMessage = formElements[i].placeholder + ' is blank';
+        errorMessages.push(errorMessage);
+      }
+    }
+  }
+}
```
Comment (areetaw) [inline src/main/webapp/assets/js/feedScript.js:806]: No more bee movie!! >:))

File: src/main/webapp/assets/css/feedStyle.css (hunk 4 above)
Comment (ubahl) [reply src/main/webapp/assets/css/feedStyle.css:210]: Thanks, it was a good idea! Thanks for creating the issue

File: src/main/webapp/find-events.html [hunk 9]
```diff
@@ -64,54 +64,57 @@ <h1 id="find-events-title" tabindex="0">find events</h1>
...
     <!-- modal -->
     <div id="modal-background">
-      <div id="modal-create-post" tabindex="0" aria-label="create a post modal">
-        <button id="modal-close" type="button" tabindex="0" aria-label="close modal">&#10005;</button>
+      <div aria-label="create a post modal" id="modal-create-post" tabindex="0">
+        <button aria-label="close modal" id="modal-close" tabindex="0" type="button">&#10005;</button>
         <h1 id="modal-title" tabindex="0">Create a Post</h1>
         <form id="modal-form" method="post">
-          <input type="text" id="modal-org-name" name="organizationName" placeholder="organization name" tabindex="0" aria-label="organization name" required><br>
+          <input aria-label="organization name" id="modal-org-name" maxlength="100" name="organizationName" placeholder="organization name" tabindex="0" type="text" required><br>
```
Comment (areetaw) [inline src/main/webapp/find-events.html:78]: Should organization name length be max 100? :0

File: src/main/webapp/assets/js/feedScript.js (hunk 5 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:133]: There is no `modal-submitted-text` id, but I can change the name of the variable to `modalSubmittedTitle` to make it more intuitive!

File: src/main/webapp/assets/js/feedScript.js (hunk 6 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:658]: Oh that changes the tags (<, >) to the HTML code for it so that someone can't inject HTML into the form!

File: src/main/webapp/assets/js/feedScript.js (hunk 7 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:798]: In Google's style guide, HTML names should be lowercase! https://google.github.io/styleguide/htmlcssguide.html#Capitalization

File: src/main/webapp/assets/js/feedScript.js (hunk 8 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:806]: 🐝 ❌

File: src/main/webapp/find-events.html (hunk 9 above)
Comment (ubahl) [reply src/main/webapp/find-events.html:78]: 100 characters is the amount of characters in this comment! I agree, I'll limit it to 50 characters.

Comment (ubahl) [reply src/main/webapp/find-events.html:78]: Fifty characters is this many words which is fine.

Comment (ubahl) [reply src/main/webapp/find-events.html:78]: So if the organizations have super long acronyms as names they can list it.

Comment (ubahl) [reply src/main/webapp/find-events.html:78]: ^ that was 75 characters 😄

File: src/main/webapp/assets/css/feedStyle.css [hunk 10]
```diff
@@ -235,7 +256,12 @@ select {
   }
 }
 
-#modal-error {
+#modal-map-error {
+  color: #b60000;
```
Comment (mrboxtobox) [inline src/main/webapp/assets/css/feedStyle.css:260]: Maybe make this a const since you reuse it.

File: src/main/webapp/assets/js/feedScript.js [hunk 11]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+  const errorMessages = [];
   const formElements = modalForm.elements;
+
+  disableInjection(formElements);
+  validateModalText(invalidIds, errorMessages, formElements);
+  validateModalDate(invalidIds, errorMessages, formElements);
+  validateModalTime(invalidIds, errorMessages, formElements);
+  markInvalidInputs(invalidIds, errorMessages, formElements);
+
+  if (invalidIds.length === 0) {
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:643]: Simplify this to `return invalidIds.lengh === 0`

File: src/main/webapp/assets/js/feedScript.js [hunk 12]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+/**
+ * Goes through the elements and replaces the tags with their HTML equivalent.
+ * @param {array} formElements
+ * @return {void}
+ */
+function disableInjection(formElements) {
   for (let i = 0; i < formElements.length - 1; i++) {
-    if (formElements[i].value.length == 0) {
-      return;
+    let eltValue = formElements[i].value;
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:657]: Could you use a clearer name for this? I'm not sure what `eltValue` stands for.

File: src/main/webapp/assets/js/feedScript.js [hunk 13]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+
+  if (invalidIds.length === 0) {
+    return true;
+  } else {
+    return false;
+  }
+}
+
+/**
+ * Goes through the elements and replaces the tags with their HTML equivalent.
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:651]: Could you explain why we need to disableInjection as well?

File: src/main/webapp/assets/js/feedScript.js [hunk 14]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+}
+
+/**
+ * Resets all the input backgrounds to modal grey and gets rid of previous error text.
+ * @param {array} formElements
+ * @return {void}
+ */
+function resetMarks(formElements) {
+  for (let i = 0; i < formElements.length - 1; i++) {
+    const elt = formElements[i];
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:669]: Same here. It will be difficult for someone who's reading this for the first time to know what elt means.

File: src/main/webapp/assets/js/feedScript.js [hunk 15]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+function validateModalTime(invalidIds, errorMessages, formElements) {
+  const startHour = parseInt(formElements.namedItem('modal-start-hour').value, 10);
+  const startMinute = parseInt(formElements.namedItem('modal-start-minute').value, 10);
+  const startAMorPM = parseInt(formElements.namedItem('start-am-or-pm').value, 10);
+  const endHour = parseInt(formElements.namedItem('modal-end-hour').value, 10);
+  const endMinute = parseInt(formElements.namedItem('modal-end-minute').value, 10);
+  const endAMorPM = parseInt(formElements.namedItem('end-am-or-pm').value, 10);
+
+  // Check if the hours fall between 1-12.
+  if (startHour < 1 || startHour > 12 || isNaN(startHour)) {
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:744]: I would put isNan first. In some languages, if you try comparing a non-number with a number, you might error out so you want to check that it's a number first.

Comment (mrboxtobox) [reply src/main/webapp/assets/js/feedScript.js:744]: Apply this below as well.

File: src/main/webapp/assets/js/feedScript.js [hunk 16]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+    invalidIds.push('modal-start-hour');
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:745]: This is clever

File: src/main/webapp/assets/js/feedScript.js [hunk 17]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+}
+
+/**
+ * Checks if the given input is blank.
+ * @param {String} input
+ * @return {void}
+ */
+function isBlank(input) {
+  const trimmed = input.trim();
+  if (trimmed) {
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:782]: `return !trimmed`

File: src/main/webapp/assets/js/feedScript.js [hunk 18]
```diff
@@ -605,16 +614,204 @@ function closeModal() {
...
+  if (startMinute < 0 || startMinute >= 60 || isNaN(startMinute)) {
+    invalidIds.push('modal-start-minute');
+    errorMessages.push('start minute must be between 00 - 59');
+  }
+  if (endMinute < 0 || endMinute >= 60 || isNaN(startMinute)) {
+    invalidIds.push('modal-end-minute');
+    errorMessages.push('end minute must be between 00 - 59');
+  }
+  // Check if the end time is after the start time.
+  if ((startAMorPM === 'pm' && endAMorPM === 'am') ||
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:762]: To improve readability I would recommend extracting some of these into variables and doing the or-check. Naming the variables would probably be the hardest part.

File: src/main/webapp/assets/js/feedScript.js [hunk 19]
```diff
@@ -628,32 +825,48 @@ async function submitModal() {
...
       url = `/postData?collegeId=${collegeId}&lat=${lat}&lng=${lng}`;
       modalForm.action = url;
-      modalForm.submit();
-      createPostButton.focus();
+
+      // Show submitted box.
+      modalCard.style.display = 'none';
+      modalSubmitted.style.display = 'block';
+      modalSubmitted.focus();
+      setTimeout(function() {
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:853]: Could

File: src/main/webapp/assets/css/feedStyle.css (hunk 10 above)
Comment (ubahl) [reply src/main/webapp/assets/css/feedStyle.css:260]: good idea!

Comment (ubahl) [reply src/main/webapp/assets/css/feedStyle.css:260]: I ended up combining the two definitions since they have the exact same attributes!

File: src/main/webapp/assets/js/feedScript.js (hunk 11 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:643]: good catch!!

File: src/main/webapp/assets/js/feedScript.js (hunk 12 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:657]: Yes, I'll change it to elementValue!

File: src/main/webapp/assets/js/feedScript.js (hunk 14 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:669]: Sounds good, I'll change it to element!

File: src/main/webapp/assets/js/feedScript.js (hunk 15 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:744]: Great point!

File: src/main/webapp/assets/js/feedScript.js (hunk 16 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:745]: Thanks!!

File: src/main/webapp/assets/js/feedScript.js (hunk 17 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:782]: Nice, thanks!

File: src/main/webapp/assets/js/feedScript.js (hunk 18 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:762]: Great idea! I'll make the change.

File: src/main/webapp/assets/js/feedScript.js (hunk 19 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:853]: It closes the form modal and shows the submit message! Added a comment in the code to increase readability.

File: src/main/webapp/assets/js/feedScript.js (hunk 13 above)
Comment (ubahl) [reply src/main/webapp/assets/js/feedScript.js:651]: Good point, I'll elaborate more in the comment!
