### PR TITLE
Fix small bugs with smart time filling and index page map

### LINKED ISSUE #99: Smart Time Error at Midnight
The smart time input has an error at Midnight. The input suggests 0 as the hour instead of 12. When attempting to submit, the modal does not accept the 0.

Possible solution: suggest 11:59am instead of 12:00am.

Screenshot 2020-08-29 at 11 08 24 PM
Screenshot 2020-08-30 at 12 11 21 AM

### PR DESCRIPTION
**Pull request by mirrorkeydev**
Tiny PR :)

## Fixed smart time error
I forgot that in the U.S., midnight is 12:00am and not 00:00. This has been fixed. Additionally, the date field now populates with today's date. Resolves #99.

image

## Fixed 'randomness' on index page map
I realized that by iterating through allColleges and checking how far away they were from a seed college, we were unintentionally favoring the colleges at the beginning of the list (starting with A). Now, each new college is randomly selected from the list and checked for distance against the seed college, providing a better overall distribution.

image

### CODE REVIEW

File: src/main/webapp/assets/js/feedScript.js [hunk 1]
```diff
@@ -1237,24 +1237,30 @@ function limitCharacterInput(e) {
...
   const modalEndHour = document.getElementById('modal-end-hour');
   const modalEndMinute = document.getElementById('modal-end-minute');
   const endAmOrPm = document.getElementById('end-am-or-pm');
 
+  modalMonth.value = new Date().getMonth() + 1; // Months are indexed at 0
+  modalDay.value = new Date().getDate();
+
   const nowHours = parseInt(new Date().getHours());
-  modalStartHour.value = nowHours > 12 ? nowHours - 12 : nowHours;
+  modalStartHour.value = nowHours > 12 ? nowHours - 12 : (nowHours !== 0 ? nowHours : 12);
```
Comment (mrboxtobox) [inline src/main/webapp/assets/js/feedScript.js:1257]: Explain what this does to make it clearer for anyone reading this with not much context.

Comment (mirrorkeydev) [reply src/main/webapp/assets/js/feedScript.js:1257]: Will do!
